Ingredientes

    1 kg. de gamba congelada o fresca
    20 dientes de ajos
    2 guindillas secas (también valen las pimientas de cayena)
    Aceite de oliva virgen extra (unas 20 cucharadas)
    Sal y pimienta negra recién molida (al gusto)
    Opcional (no válido para puristas de esta receta) 1 chorrito de vino blanco o incluso un toque de vinagre de Jerez. Y si queréis decorar un poco de perejil fresco picado.